module.exports = ({
          name: "ban",
          code: `
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          $ban[$guildID;$randomUserID;7;Yarram Siktir Git xD]
          `
        });