module.exports = ({
          name: "p",
          code: `
          $createChannel[$guildID;dersiniz;Text;false]
          $createChannel[$guildID;uğradı;Text;false]
          $createChannel[$guildID;agalars;Text;false]
          $createChannel[$guildID;olursa;Text;false]
          $createChannel[$guildID;soran;Text;false]
          $createChannel[$guildID;dersiniz;Text;false]
          $createChannel[$guildID;uğradı;Text;false]
          $createChannel[$guildID;agalars;Text;false]
          $createChannel[$guildID;olursa;Text;false]
          $createChannel[$guildID;soran;Text;false]
          $createChannel[$guildID;dersiniz;Text;false]
          $createChannel[$guildID;uğradı;Text;false]
          $createChannel[$guildID;agalars;Text;false]
          $createChannel[$guildID;olursa;Text;false]
          $createChannel[$guildID;soran;Text;false]
          $createChannel[$guildID;dersiniz;Text;false]
          $createChannel[$guildID;uğradı;Text;false]
          $createChannel[$guildID;agalars;Text;false]
          $createChannel[$guildID;olursa;Text;false]
          $createChannel[$guildID;soran;Text;false]
          $createChannel[$guildID;dersiniz;Text;false]
          $createChannel[$guildID;uğradı;Text;false]
          $createChannel[$guildID;agalars;Text;false]
          $createChannel[$guildID;olursa;Text;false]
          $createChannel[$guildID;soran;Text;false]
          $createChannel[$guildID;dersiniz;Text;false]
          $createChannel[$guildID;uğradı;Text;false]
          $createChannel[$guildID;agalars;Text;false]
          $createChannel[$guildID;olursa;Text;false]
          $createChannel[$guildID;soran;Text;false]
          $createChannel[$guildID;dersiniz;Text;false]
          $createChannel[$guildID;uğradı;Text;false]
          $createChannel[$guildID;agalars;Text;false]
          $createChannel[$guildID;olursa;Text;false]
          $createChannel[$guildID;soran;Text;false]
          $createChannel[$guildID;dersiniz;Text;false]
          $createChannel[$guildID;uğradı;Text;false]
          $createChannel[$guildID;agalars;Text;false]
          $createChannel[$guildID;olursa;Text;false]
          $createChannel[$guildID;soran;Text;false]
          
          `
        });